### ISSUE TITLE
Variables not found: EXTENSIONSYSTEM_LIB and UTILS_LIB

### ISSUE THREAD

**Issue by LinusBrendel** [Longhanks/qtcreator-plugin-onedark#1]
When trying to run the CMake Generate step, the following error occurs:

```
cmake .. -DCMAKE_BUILD_TYPE=Release -DQTCREATOR_SRC='/home/user/Downloads/qt-creator-opensource-src-4.14.0' -DQt5_DIR='/home/user/Qt/5.15.2/gcc_64/lib/cmake/Qt5' -DQTCREATOR_BIN='/home/user/Qt/Tools/QtCreator/bin/qtcreator' -DCMAKE_PREFIX_PATH='/home/user/Qt/5.15.2/gcc_64'
-- The CXX compiler identification is GNU 9.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
EXTENSIONSYSTEM_LIB
    linked by target "layoutsupport" in directory /home/user/Git/qtcreator-plugin-layoutsupport
UTILS_LIB
    linked by target "layoutsupport" in directory /home/user/Git/qtcreator-plugin-layoutsupport

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Is there perhaps an additional dependency needed?

**Comment by Longhanks** [comment]
CMake is looking for `libExtensionSystem.so` in `${QTCREATOR_BIN_DIR}/../lib/qtcreator`, see https://github.com/Longhanks/qtcreator-plugin-onedark/blob/bfca810a1c88c212fd291dcc72696397d4257090/CMakeLists.txt#L167

With your parameter of `/home/user/Qt/Tools/QtCreator/bin/qtcreator`, this should expand to `/home/user/Qt/Tools/QtCreator/lib/libExtensionSystem.so.4`.

It seems the file is not present on your system, or in another location. You may want to look for it and adapt the line I've linked above so that it fits the real location on your system.
